workflows:
  build-android:
    name: Build APK
    environment:
      android: true
      java: 17
    scripts:
      - name: Make Gradle executable
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/**/outputs/**/*.apk
