name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Construir APK
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug

    - name: Subir APK
      uses: actions/upload-artifact@v4
      with:
        name: navegador-streaming-apk
        path: app/build/outputs/apk/debug/app-debug.apk
